[package]
name="appy"
version="0.1.1"
edition="2021"
description="Declarative UI framework with native rendering"
documentation = "https://docs.rs/appy"
homepage = "https://github.com/limikael/appy"
repository = "https://github.com/limikael/appy"
license = "MIT"

[lib]
name="appy"
path="src/lib.rs"

[dependencies]
appy-macros = {version="0.1.0", path="./appy-macros"}
gl = "0.14.0"
nalgebra-glm = "0.18.0"
rusttype = {version="0.9.3", features=["gpu_cache"]}
environmental = "1.1.4"

# SDL deps
sdl2 = {version="0.35.2", optional=true}

# Glutin deps
glutin = {version="0.30.7", optional=true}
winit = {version="0.28.3", features=["android-native-activity"], optional=true}
glutin-winit = {version="0.3.0", optional=true}
raw-window-handle = {version="0.5.2", optional=true}

# Glium deps
#glium={version="0.32.1",optional=true}

[target.'cfg(target_os="android")'.dependencies]
android_log-sys = "0.3.0"
libc = "0.2.141"

[features]
#default=["sdl"]
sdl=["dep:sdl2", "appy-macros/sdl"]
glutin=["dep:glutin", "dep:winit", "dep:glutin-winit", "dep:raw-window-handle", "appy-macros/glutin"]
