[package]
name = "hello-button"
version = "0.1.0"
edition = "2021"

[package.metadata]
appid="com.example.hellobutton"
appname="Hello Button"

[lib]
path="src/main.rs"
crate-type=["cdylib"]

[dependencies]
appy = {path="../..", features=["sdl"]}
